[0m11:16:48.771885 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087d8830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10962b750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10962b9d0>]}


============================== 11:16:48.774866 | 0475f59e-b43c-4076-84f3-dd2f30a00a4b ==============================
[0m11:16:48.774866 [info ] [MainThread]: Running with dbt=1.10.13
[0m11:16:48.775174 [debug] [MainThread]: running dbt with arguments {'log_path': 'logs', 'indirect_selection': 'eager', 'write_json': 'True', 'version_check': 'True', 'debug': 'False', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'no_print': 'None', 'cache_selected_only': 'False', 'warn_error': 'None', 'profiles_dir': '/Users/barbaramariano/.dbt', 'empty': 'None', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'use_colors': 'True', 'static_parser': 'True', 'log_cache_events': 'False', 'introspect': 'True', 'printer_width': '80', 'log_format': 'default', 'invocation_command': 'dbt debug', 'use_experimental_parser': 'False', 'fail_fast': 'False', 'target_path': 'None'}
[0m11:16:48.789375 [info ] [MainThread]: dbt version: 1.10.13
[0m11:16:48.789584 [info ] [MainThread]: python version: 3.13.7
[0m11:16:48.789710 [info ] [MainThread]: python path: /Users/barbaramariano/repositories/funnel_analysis/.venv/bin/python3.13
[0m11:16:48.789833 [info ] [MainThread]: os info: macOS-13.4-arm64-arm-64bit-Mach-O
[0m11:16:48.789953 [info ] [MainThread]: Using profiles dir at /Users/barbaramariano/.dbt
[0m11:16:48.790060 [info ] [MainThread]: Using profiles.yml file at /Users/barbaramariano/.dbt/profiles.yml
[0m11:16:48.790165 [info ] [MainThread]: Using dbt_project.yml file at /Users/barbaramariano/repositories/funnel_analysis/dbt_project.yml
[0m11:16:48.790277 [info ] [MainThread]: Configuration:
[0m11:16:48.790377 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m11:16:48.790478 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m11:16:48.790579 [info ] [MainThread]: Required dependencies:
[0m11:16:48.790713 [debug] [MainThread]: Executing "git --help"
[0m11:16:48.816741 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:16:48.817376 [debug] [MainThread]: STDERR: "b''"
[0m11:16:48.817598 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:16:48.817774 [info ] [MainThread]: Connection test skipped since no profile was found
[0m11:16:48.817991 [info ] [MainThread]: [31m2 checks failed:[0m
[0m11:16:48.818124 [info ] [MainThread]: dbt looked for a profiles.yml file in /Users/barbaramariano/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m11:16:48.818250 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/barbaramariano/repositories/funnel_analysis/dbt_project.yml> not found

[0m11:16:48.831903 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.09492396, "process_in_blocks": "0", "process_kernel_time": 0.137917, "process_mem_max_rss": "104005632", "process_out_blocks": "0", "process_user_time": 0.755458}
[0m11:16:48.832305 [debug] [MainThread]: Command `dbt debug` failed at 11:16:48.832240 after 0.10 seconds
[0m11:16:48.832620 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109718510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10952b1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094cb350>]}
[0m11:16:48.832852 [debug] [MainThread]: Flushing usage events
[0m11:16:49.312213 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:18:59.627619 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d141a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f5f890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f5f9d0>]}


============================== 11:18:59.630828 | 3624fa9a-a605-4d43-a78e-7a0cf5653994 ==============================
[0m11:18:59.630828 [info ] [MainThread]: Running with dbt=1.10.13
[0m11:18:59.631164 [debug] [MainThread]: running dbt with arguments {'log_path': '/Users/barbaramariano/repositories/funnel_analysis/logs', 'static_parser': 'True', 'fail_fast': 'False', 'warn_error': 'None', 'log_format': 'default', 'printer_width': '80', 'cache_selected_only': 'False', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'use_colors': 'True', 'target_path': 'None', 'version_check': 'True', 'no_print': 'None', 'use_experimental_parser': 'False', 'write_json': 'True', 'indirect_selection': 'eager', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True', 'quiet': 'False', 'empty': 'None', 'debug': 'False', 'profiles_dir': '/Users/barbaramariano/.dbt', 'log_cache_events': 'False', 'introspect': 'True'}
[0m11:18:59.645719 [info ] [MainThread]: dbt version: 1.10.13
[0m11:18:59.645938 [info ] [MainThread]: python version: 3.13.7
[0m11:18:59.646069 [info ] [MainThread]: python path: /Users/barbaramariano/repositories/funnel_analysis/.venv/bin/python3.13
[0m11:18:59.646186 [info ] [MainThread]: os info: macOS-13.4-arm64-arm-64bit-Mach-O
[0m11:18:59.646307 [info ] [MainThread]: Using profiles dir at /Users/barbaramariano/.dbt
[0m11:18:59.646419 [info ] [MainThread]: Using profiles.yml file at /Users/barbaramariano/.dbt/profiles.yml
[0m11:18:59.646542 [info ] [MainThread]: Using dbt_project.yml file at /Users/barbaramariano/repositories/funnel_analysis/dbt_project.yml
[0m11:18:59.691700 [info ] [MainThread]: Configuration:
[0m11:18:59.691929 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m11:18:59.692072 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m11:18:59.692192 [info ] [MainThread]: Required dependencies:
[0m11:18:59.692364 [debug] [MainThread]: Executing "git --help"
[0m11:18:59.703362 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:18:59.703893 [debug] [MainThread]: STDERR: "b''"
[0m11:18:59.704066 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:18:59.704214 [info ] [MainThread]: Connection test skipped since no profile was found
[0m11:18:59.704344 [info ] [MainThread]: [31m1 check failed:[0m
[0m11:18:59.704460 [info ] [MainThread]: dbt looked for a profiles.yml file in /Users/barbaramariano/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m11:18:59.706437 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.12006175, "process_in_blocks": "0", "process_kernel_time": 0.11895, "process_mem_max_rss": "106496000", "process_out_blocks": "0", "process_user_time": 0.652735}
[0m11:18:59.706743 [debug] [MainThread]: Command `dbt debug` failed at 11:18:59.706691 after 0.12 seconds
[0m11:18:59.706983 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e5bbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11891b9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107de6e00>]}
[0m11:18:59.707196 [debug] [MainThread]: Flushing usage events
[0m11:19:00.153929 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:24:18.304007 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1061e41a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10702b890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10702b9d0>]}


============================== 11:24:18.307131 | 1d1da481-4ab2-4db6-aef7-71a3c9e024ad ==============================
[0m11:24:18.307131 [info ] [MainThread]: Running with dbt=1.10.13
[0m11:24:18.307484 [debug] [MainThread]: running dbt with arguments {'empty': 'None', 'indirect_selection': 'eager', 'profiles_dir': '/Users/barbaramariano/.dbt', 'log_cache_events': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'partial_parse': 'True', 'invocation_command': 'dbt debug', 'version_check': 'True', 'quiet': 'False', 'write_json': 'True', 'use_experimental_parser': 'False', 'log_path': '/Users/barbaramariano/repositories/funnel_analysis/logs', 'send_anonymous_usage_stats': 'True', 'target_path': 'None', 'static_parser': 'True', 'debug': 'False', 'log_format': 'default', 'cache_selected_only': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'printer_width': '80', 'use_colors': 'True', 'introspect': 'True'}
[0m11:24:18.322375 [info ] [MainThread]: dbt version: 1.10.13
[0m11:24:18.322618 [info ] [MainThread]: python version: 3.13.7
[0m11:24:18.322757 [info ] [MainThread]: python path: /Users/barbaramariano/repositories/funnel_analysis/.venv/bin/python3.13
[0m11:24:18.322882 [info ] [MainThread]: os info: macOS-13.4-arm64-arm-64bit-Mach-O
[0m11:24:34.029975 [info ] [MainThread]: Using profiles dir at /Users/barbaramariano/.dbt
[0m11:24:34.030455 [info ] [MainThread]: Using profiles.yml file at /Users/barbaramariano/.dbt/profiles.yml
[0m11:24:34.030599 [info ] [MainThread]: Using dbt_project.yml file at /Users/barbaramariano/repositories/funnel_analysis/dbt_project.yml
[0m11:24:34.030724 [info ] [MainThread]: adapter type: bigquery
[0m11:24:34.030868 [info ] [MainThread]: adapter version: 1.10.2
[0m11:24:34.079733 [info ] [MainThread]: Configuration:
[0m11:24:34.080019 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m11:24:34.080167 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m11:24:34.080293 [info ] [MainThread]: Required dependencies:
[0m11:24:34.080482 [debug] [MainThread]: Executing "git --help"
[0m11:24:34.106616 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:24:34.107176 [debug] [MainThread]: STDERR: "b''"
[0m11:24:34.107351 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:24:34.107508 [info ] [MainThread]: Connection:
[0m11:24:34.107674 [info ] [MainThread]:   method: oauth
[0m11:24:34.107794 [info ] [MainThread]:   database: funnel-analysis-473408
[0m11:24:34.107914 [info ] [MainThread]:   execution_project: funnel-analysis-473408
[0m11:24:34.108019 [info ] [MainThread]:   schema: analytics
[0m11:24:34.108116 [info ] [MainThread]:   location: EU
[0m11:24:34.108215 [info ] [MainThread]:   priority: interactive
[0m11:24:34.108319 [info ] [MainThread]:   maximum_bytes_billed: None
[0m11:24:34.108419 [info ] [MainThread]:   impersonate_service_account: None
[0m11:24:34.108518 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m11:24:34.108618 [info ] [MainThread]:   job_retries: 1
[0m11:24:34.108715 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m11:24:34.108811 [info ] [MainThread]:   job_execution_timeout_seconds: None
[0m11:24:34.108909 [info ] [MainThread]:   timeout_seconds: None
[0m11:24:34.109007 [info ] [MainThread]:   client_id: None
[0m11:24:34.109101 [info ] [MainThread]:   token_uri: None
[0m11:24:34.109198 [info ] [MainThread]:   compute_region: None
[0m11:24:34.109292 [info ] [MainThread]:   dataproc_cluster_name: None
[0m11:24:34.109388 [info ] [MainThread]:   gcs_bucket: None
[0m11:24:34.109484 [info ] [MainThread]:   dataproc_batch: None
[0m11:24:34.109828 [info ] [MainThread]: Registered adapter: bigquery=1.10.2
[0m11:24:34.296863 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m11:24:34.297346 [debug] [MainThread]: On debug: select 1 as id
[0m11:24:34.297542 [debug] [MainThread]: Opening a new connection, currently in state init
[0m11:24:43.379312 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Runtime Error
  Failed to authenticate with supplied credentials
  error:
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.'
[0m11:24:43.381982 [debug] [MainThread]: BigQuery adapter: Unhandled error while running:
select 1 as id
[0m11:24:43.383045 [debug] [MainThread]: BigQuery adapter: Database Error
  Runtime Error
    Failed to authenticate with supplied credentials
    error:
    Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[0m11:24:43.384436 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m11:24:43.385248 [info ] [MainThread]: [31m1 check failed:[0m
[0m11:24:43.385626 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >'NoneType' object has no attribute 'close'

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m11:24:43.391974 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 25.121424, "process_in_blocks": "0", "process_kernel_time": 0.681106, "process_mem_max_rss": "338903040", "process_out_blocks": "0", "process_user_time": 3.183402}
[0m11:24:43.394999 [debug] [MainThread]: Command `dbt debug` failed at 11:24:43.394758 after 25.13 seconds
[0m11:24:43.396178 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x168026520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16808e450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1466b8d10>]}
[0m11:24:43.396867 [debug] [MainThread]: Flushing usage events
[0m11:24:43.893499 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:30:21.941956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062dc1a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107c5f890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107c5f9d0>]}


============================== 11:30:21.945814 | 685da97c-8971-47b7-9984-64adbcdf5803 ==============================
[0m11:30:21.945814 [info ] [MainThread]: Running with dbt=1.10.13
[0m11:30:21.946133 [debug] [MainThread]: running dbt with arguments {'log_cache_events': 'False', 'version_check': 'True', 'send_anonymous_usage_stats': 'True', 'quiet': 'False', 'log_format': 'default', 'empty': 'None', 'cache_selected_only': 'False', 'warn_error': 'None', 'target_path': 'None', 'use_colors': 'True', 'indirect_selection': 'eager', 'partial_parse': 'True', 'write_json': 'True', 'use_experimental_parser': 'False', 'static_parser': 'True', 'fail_fast': 'False', 'printer_width': '80', 'log_path': '/Users/barbaramariano/repositories/funnel_analysis/logs', 'no_print': 'None', 'debug': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'profiles_dir': '/Users/barbaramariano/.dbt', 'introspect': 'True', 'invocation_command': 'dbt debug'}
[0m11:30:21.959726 [info ] [MainThread]: dbt version: 1.10.13
[0m11:30:21.959943 [info ] [MainThread]: python version: 3.13.7
[0m11:30:21.960074 [info ] [MainThread]: python path: /Users/barbaramariano/repositories/funnel_analysis/.venv/bin/python3.13
[0m11:30:21.960193 [info ] [MainThread]: os info: macOS-13.4-arm64-arm-64bit-Mach-O
[0m11:30:23.589475 [info ] [MainThread]: Using profiles dir at /Users/barbaramariano/.dbt
[0m11:30:23.589758 [info ] [MainThread]: Using profiles.yml file at /Users/barbaramariano/.dbt/profiles.yml
[0m11:30:23.589934 [info ] [MainThread]: Using dbt_project.yml file at /Users/barbaramariano/repositories/funnel_analysis/dbt_project.yml
[0m11:30:23.590109 [info ] [MainThread]: adapter type: bigquery
[0m11:30:23.590238 [info ] [MainThread]: adapter version: 1.10.2
[0m11:30:23.644166 [info ] [MainThread]: Configuration:
[0m11:30:23.644642 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m11:30:23.644827 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m11:30:23.644964 [info ] [MainThread]: Required dependencies:
[0m11:30:23.645166 [debug] [MainThread]: Executing "git --help"
[0m11:30:23.671635 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:30:23.672181 [debug] [MainThread]: STDERR: "b''"
[0m11:30:23.672360 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:30:23.672520 [info ] [MainThread]: Connection:
[0m11:30:23.672706 [info ] [MainThread]:   method: oauth
[0m11:30:23.672830 [info ] [MainThread]:   database: funnel-analysis-473408
[0m11:30:23.672952 [info ] [MainThread]:   execution_project: funnel-analysis-473408
[0m11:30:23.673066 [info ] [MainThread]:   schema: analytics
[0m11:30:23.673176 [info ] [MainThread]:   location: europe-west9
[0m11:30:23.673287 [info ] [MainThread]:   priority: interactive
[0m11:30:23.673396 [info ] [MainThread]:   maximum_bytes_billed: None
[0m11:30:23.673502 [info ] [MainThread]:   impersonate_service_account: None
[0m11:30:23.673612 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m11:30:23.673716 [info ] [MainThread]:   job_retries: 1
[0m11:30:23.673823 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m11:30:23.673929 [info ] [MainThread]:   job_execution_timeout_seconds: None
[0m11:30:23.674033 [info ] [MainThread]:   timeout_seconds: None
[0m11:30:23.674143 [info ] [MainThread]:   client_id: None
[0m11:30:23.674246 [info ] [MainThread]:   token_uri: None
[0m11:30:23.674351 [info ] [MainThread]:   compute_region: None
[0m11:30:23.674457 [info ] [MainThread]:   dataproc_cluster_name: None
[0m11:30:23.674561 [info ] [MainThread]:   gcs_bucket: None
[0m11:30:23.674667 [info ] [MainThread]:   dataproc_batch: None
[0m11:30:23.674989 [info ] [MainThread]: Registered adapter: bigquery=1.10.2
[0m11:30:23.834933 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m11:30:23.835254 [debug] [MainThread]: On debug: select 1 as id
[0m11:30:23.835410 [debug] [MainThread]: Opening a new connection, currently in state init
[0m11:30:32.657169 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Runtime Error
  Failed to authenticate with supplied credentials
  error:
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.'
[0m11:30:32.660111 [debug] [MainThread]: BigQuery adapter: Unhandled error while running:
select 1 as id
[0m11:30:32.660693 [debug] [MainThread]: BigQuery adapter: Database Error
  Runtime Error
    Failed to authenticate with supplied credentials
    error:
    Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[0m11:30:32.662084 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m11:30:32.662997 [info ] [MainThread]: [31m1 check failed:[0m
[0m11:30:32.663429 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >'NoneType' object has no attribute 'close'

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m11:30:32.671010 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 10.767146, "process_in_blocks": "0", "process_kernel_time": 0.588169, "process_mem_max_rss": "348405760", "process_out_blocks": "0", "process_user_time": 3.12048}
[0m11:30:32.674950 [debug] [MainThread]: Command `dbt debug` failed at 11:30:32.674604 after 10.77 seconds
[0m11:30:32.676421 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x160326190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16038e570>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16046cc00>]}
[0m11:30:32.677263 [debug] [MainThread]: Flushing usage events
[0m11:30:33.188061 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:30:34.581496 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d901a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bdf890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bdf9d0>]}


============================== 11:30:34.584166 | a2a159ea-0bbf-40f6-a98f-46cc07511d2d ==============================
[0m11:30:34.584166 [info ] [MainThread]: Running with dbt=1.10.13
[0m11:30:34.584467 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'introspect': 'True', 'use_experimental_parser': 'False', 'warn_error': 'None', 'profiles_dir': '/Users/barbaramariano/.dbt', 'fail_fast': 'False', 'partial_parse': 'True', 'no_print': 'None', 'log_path': '/Users/barbaramariano/repositories/funnel_analysis/logs', 'debug': 'False', 'log_cache_events': 'False', 'empty': 'None', 'send_anonymous_usage_stats': 'True', 'cache_selected_only': 'False', 'write_json': 'True', 'indirect_selection': 'eager', 'version_check': 'True', 'use_colors': 'True', 'invocation_command': 'dbt seed', 'printer_width': '80', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_format': 'default', 'target_path': 'None'}
[0m11:30:36.031844 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'a2a159ea-0bbf-40f6-a98f-46cc07511d2d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ed3bb0>]}
[0m11:30:36.057978 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'a2a159ea-0bbf-40f6-a98f-46cc07511d2d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x169c6d370>]}
[0m11:30:36.058275 [info ] [MainThread]: Registered adapter: bigquery=1.10.2
[0m11:30:36.238142 [debug] [MainThread]: checksum: 9f0c81e2574b4ff463f3d16d080df83c6982fc0372c9feeacae0504ac9ea3ffe, vars: {}, profile: , target: , version: 1.10.13
[0m11:30:36.238597 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m11:30:36.238785 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'a2a159ea-0bbf-40f6-a98f-46cc07511d2d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1699e7850>]}
[0m11:30:36.577581 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.funnel_analysis.marts
- models.funnel_analysis
[0m11:30:36.579797 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'a2a159ea-0bbf-40f6-a98f-46cc07511d2d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076cbc50>]}
[0m11:30:36.598764 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/barbaramariano/repositories/funnel_analysis/target/manifest.json
[0m11:30:36.599973 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/barbaramariano/repositories/funnel_analysis/target/semantic_manifest.json
[0m11:30:36.641225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'a2a159ea-0bbf-40f6-a98f-46cc07511d2d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16a196190>]}
[0m11:30:36.641502 [info ] [MainThread]: Found 495 macros
[0m11:30:36.641661 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'a2a159ea-0bbf-40f6-a98f-46cc07511d2d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16a1efba0>]}
[0m11:30:36.642317 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m11:30:36.642580 [debug] [MainThread]: Command end result
[0m11:30:36.653117 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/barbaramariano/repositories/funnel_analysis/target/manifest.json
[0m11:30:36.653984 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/barbaramariano/repositories/funnel_analysis/target/semantic_manifest.json
[0m11:30:36.655601 [debug] [MainThread]: Wrote artifact RunExecutionResult to /Users/barbaramariano/repositories/funnel_analysis/target/run_results.json
[0m11:30:36.655752 [info ] [MainThread]: 
[0m11:30:36.655941 [info ] [MainThread]: [32mCompleted successfully[0m
[0m11:30:36.656062 [info ] [MainThread]: 
[0m11:30:36.656195 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=0
[0m11:30:36.657484 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": true, "command_wall_clock_time": 2.1076741, "process_in_blocks": "0", "process_kernel_time": 0.50283, "process_mem_max_rss": "343277568", "process_out_blocks": "0", "process_user_time": 3.457809}
[0m11:30:36.657789 [debug] [MainThread]: Command `dbt seed` succeeded at 11:30:36.657743 after 2.11 seconds
[0m11:30:36.657987 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a1de50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16a1b31d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16a1b2fc0>]}
[0m11:30:36.658143 [debug] [MainThread]: Flushing usage events
[0m11:30:37.046762 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:30:38.387818 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079101a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111367890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1113679d0>]}


============================== 11:30:38.390522 | c58aa7f0-2931-43d3-83aa-0ac68937b79e ==============================
[0m11:30:38.390522 [info ] [MainThread]: Running with dbt=1.10.13
[0m11:30:38.390824 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'use_experimental_parser': 'False', 'log_path': '/Users/barbaramariano/repositories/funnel_analysis/logs', 'log_cache_events': 'False', 'profiles_dir': '/Users/barbaramariano/.dbt', 'warn_error': 'None', 'debug': 'False', 'empty': 'False', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True', 'log_format': 'default', 'quiet': 'False', 'indirect_selection': 'eager', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'no_print': 'None', 'partial_parse': 'True', 'introspect': 'True', 'printer_width': '80', 'use_colors': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'fail_fast': 'False', 'write_json': 'True', 'static_parser': 'True'}
[0m11:30:39.711225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'c58aa7f0-2931-43d3-83aa-0ac68937b79e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107a57bb0>]}
[0m11:30:39.737625 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'c58aa7f0-2931-43d3-83aa-0ac68937b79e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x171765370>]}
[0m11:30:39.737910 [info ] [MainThread]: Registered adapter: bigquery=1.10.2
[0m11:30:39.901217 [debug] [MainThread]: checksum: 9f0c81e2574b4ff463f3d16d080df83c6982fc0372c9feeacae0504ac9ea3ffe, vars: {}, profile: , target: , version: 1.10.13
[0m11:30:39.936107 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m11:30:39.936295 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m11:30:39.936576 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.funnel_analysis
- models.funnel_analysis.marts
[0m11:30:39.939009 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'c58aa7f0-2931-43d3-83aa-0ac68937b79e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16d07ae50>]}
[0m11:30:39.960642 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/barbaramariano/repositories/funnel_analysis/target/manifest.json
[0m11:30:39.961706 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/barbaramariano/repositories/funnel_analysis/target/semantic_manifest.json
[0m11:30:39.972831 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'c58aa7f0-2931-43d3-83aa-0ac68937b79e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1717c0d70>]}
[0m11:30:39.973097 [info ] [MainThread]: Found 495 macros
[0m11:30:39.973256 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'c58aa7f0-2931-43d3-83aa-0ac68937b79e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x171c260b0>]}
[0m11:30:39.973937 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m11:30:39.974888 [debug] [MainThread]: Command end result
[0m11:30:39.986001 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/barbaramariano/repositories/funnel_analysis/target/manifest.json
[0m11:30:39.987454 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/barbaramariano/repositories/funnel_analysis/target/semantic_manifest.json
[0m11:30:39.989547 [debug] [MainThread]: Wrote artifact RunExecutionResult to /Users/barbaramariano/repositories/funnel_analysis/target/run_results.json
[0m11:30:39.991029 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": true, "command_wall_clock_time": 1.6348288, "process_in_blocks": "0", "process_kernel_time": 0.770342, "process_mem_max_rss": "334331904", "process_out_blocks": "0", "process_user_time": 2.984597}
[0m11:30:39.991394 [debug] [MainThread]: Command `dbt run` succeeded at 11:30:39.991335 after 1.64 seconds
[0m11:30:39.991593 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x171c5bd40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1110a5e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16d091490>]}
[0m11:30:39.991761 [debug] [MainThread]: Flushing usage events
[0m11:30:40.375024 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:40:13.226517 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1061881a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fd7890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fd79d0>]}


============================== 11:40:13.229860 | d4b2b62f-2426-44bf-aa43-ff10aeabf134 ==============================
[0m11:40:13.229860 [info ] [MainThread]: Running with dbt=1.10.13
[0m11:40:13.230303 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'partial_parse': 'True', 'invocation_command': 'dbt seed', 'printer_width': '80', 'log_format': 'default', 'empty': 'None', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'cache_selected_only': 'False', 'introspect': 'True', 'target_path': 'None', 'use_colors': 'True', 'debug': 'False', 'log_cache_events': 'False', 'quiet': 'False', 'warn_error': 'None', 'use_experimental_parser': 'False', 'no_print': 'None', 'profiles_dir': '/Users/barbaramariano/.dbt', 'fail_fast': 'False', 'indirect_selection': 'eager', 'version_check': 'True', 'log_path': '/Users/barbaramariano/repositories/funnel_analysis/logs'}
[0m11:40:14.969371 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'd4b2b62f-2426-44bf-aa43-ff10aeabf134', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062cbbb0>]}
[0m11:40:14.995435 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'd4b2b62f-2426-44bf-aa43-ff10aeabf134', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x14fe65370>]}
[0m11:40:14.995743 [info ] [MainThread]: Registered adapter: bigquery=1.10.2
[0m11:40:15.162706 [debug] [MainThread]: checksum: 9f0c81e2574b4ff463f3d16d080df83c6982fc0372c9feeacae0504ac9ea3ffe, vars: {}, profile: , target: , version: 1.10.13
[0m11:40:15.200574 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 1 files added, 0 files changed.
[0m11:40:15.200813 [debug] [MainThread]: Partial parsing: added file: funnel_analysis://seeds/events.csv
[0m11:40:15.291398 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.funnel_analysis
- models.funnel_analysis.marts
[0m11:40:15.293742 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'd4b2b62f-2426-44bf-aa43-ff10aeabf134', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x14fde7750>]}
[0m11:40:15.320431 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/barbaramariano/repositories/funnel_analysis/target/manifest.json
[0m11:40:15.322143 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/barbaramariano/repositories/funnel_analysis/target/semantic_manifest.json
[0m11:40:15.332915 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'd4b2b62f-2426-44bf-aa43-ff10aeabf134', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1603e9d60>]}
[0m11:40:15.333147 [info ] [MainThread]: Found 1 seed, 495 macros
[0m11:40:15.333307 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'd4b2b62f-2426-44bf-aa43-ff10aeabf134', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x160167cb0>]}
[0m11:40:15.334365 [info ] [MainThread]: 
[0m11:40:15.334536 [info ] [MainThread]: Concurrency: 4 threads (target='prod')
[0m11:40:15.334658 [info ] [MainThread]: 
[0m11:40:15.334887 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m11:40:15.335280 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_funnel-analysis-473408'
[0m11:40:15.335462 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:40:21.245144 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Runtime Error
  Failed to authenticate with supplied credentials
  error:
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.'
[0m11:40:21.249585 [debug] [MainThread]: Opening a new connection, currently in state init
[0m11:40:24.312565 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Runtime Error
  Failed to authenticate with supplied credentials
  error:
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.'
[0m11:40:24.314690 [info ] [MainThread]: 
[0m11:40:24.315666 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 8.98 seconds (8.98s).
[0m11:40:24.318019 [error] [MainThread]: Encountered an error:
Database Error
  Runtime Error
    Failed to authenticate with supplied credentials
    error:
    Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[0m11:40:24.326917 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 11.135815, "process_in_blocks": "0", "process_kernel_time": 0.65527, "process_mem_max_rss": "352763904", "process_out_blocks": "0", "process_user_time": 3.240623}
[0m11:40:24.330835 [debug] [MainThread]: Command `dbt seed` failed at 11:40:24.330315 after 11.14 seconds
[0m11:40:24.332306 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16064c6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e19e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16062b950>]}
[0m11:40:24.333406 [debug] [MainThread]: Flushing usage events
[0m11:40:24.820584 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:00:40.259998 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1064141a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f67890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f679d0>]}


============================== 12:00:40.263077 | 690d303f-8805-4af5-a6a9-a783c6cf1f6e ==============================
[0m12:00:40.263077 [info ] [MainThread]: Running with dbt=1.10.13
[0m12:00:40.263394 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'log_cache_events': 'False', 'version_check': 'True', 'empty': 'None', 'invocation_command': 'dbt seed', 'debug': 'False', 'indirect_selection': 'eager', 'quiet': 'False', 'no_print': 'None', 'log_path': '/Users/barbaramariano/repositories/funnel_analysis/logs', 'cache_selected_only': 'False', 'write_json': 'True', 'static_parser': 'True', 'fail_fast': 'False', 'log_format': 'default', 'profiles_dir': '/Users/barbaramariano/.dbt', 'target_path': 'None', 'use_experimental_parser': 'False', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'partial_parse': 'True', 'use_colors': 'True'}
[0m12:00:41.983740 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '690d303f-8805-4af5-a6a9-a783c6cf1f6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106657bb0>]}
[0m12:00:42.010582 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '690d303f-8805-4af5-a6a9-a783c6cf1f6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15df65370>]}
[0m12:00:42.010920 [info ] [MainThread]: Registered adapter: bigquery=1.10.2
[0m12:00:42.199352 [debug] [MainThread]: checksum: 9f0c81e2574b4ff463f3d16d080df83c6982fc0372c9feeacae0504ac9ea3ffe, vars: {}, profile: , target: , version: 1.10.13
[0m12:00:42.251197 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m12:00:42.251507 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m12:00:42.254552 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.funnel_analysis
- models.funnel_analysis.marts
[0m12:00:42.263555 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '690d303f-8805-4af5-a6a9-a783c6cf1f6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15dee7150>]}
[0m12:00:42.292672 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/barbaramariano/repositories/funnel_analysis/target/manifest.json
[0m12:00:42.294279 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/barbaramariano/repositories/funnel_analysis/target/semantic_manifest.json
[0m12:00:42.306602 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '690d303f-8805-4af5-a6a9-a783c6cf1f6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15e4e5a90>]}
[0m12:00:42.306842 [info ] [MainThread]: Found 1 seed, 495 macros
[0m12:00:42.306997 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '690d303f-8805-4af5-a6a9-a783c6cf1f6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15e61eb30>]}
[0m12:00:42.307762 [info ] [MainThread]: 
[0m12:00:42.307938 [info ] [MainThread]: Concurrency: 4 threads (target='prod')
[0m12:00:42.308055 [info ] [MainThread]: 
[0m12:00:42.308277 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m12:00:42.308695 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_funnel-analysis-473408'
[0m12:00:42.308898 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m12:00:43.153721 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_funnel-analysis-473408, now list_funnel-analysis-473408_analytics)
[0m12:00:43.154969 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m12:00:43.329486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '690d303f-8805-4af5-a6a9-a783c6cf1f6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15e63ce20>]}
[0m12:00:43.330583 [debug] [MainThread]: Opening a new connection, currently in state init
[0m12:00:43.338500 [debug] [Thread-1 (]: Began running node seed.funnel_analysis.events
[0m12:00:43.339569 [info ] [Thread-1 (]: 1 of 1 START seed file analytics.events ........................................ [RUN]
[0m12:00:43.340350 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_funnel-analysis-473408_analytics, now seed.funnel_analysis.events)
[0m12:00:43.340849 [debug] [Thread-1 (]: Began compiling node seed.funnel_analysis.events
[0m12:00:43.341210 [debug] [Thread-1 (]: Began executing node seed.funnel_analysis.events
[0m12:00:43.410953 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m12:00:45.052017 [error] [Thread-1 (]: [31mUnhandled error while executing [0m
400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 9; errors: 9; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 9; errors: 9; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:10:00Z"; line_number: 2 byte_offset_to_start_of_line: 50 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:10:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:15:00Z"; line_number: 3 byte_offset_to_start_of_line: 89 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:15:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T09:00:00Z"; line_number: 4 byte_offset_to_start_of_line: 139 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T09:00:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-21T10:20:00Z"; line_number: 5 byte_offset_to_start_of_line: 182 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-21T10:20:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:12:00Z"; line_number: 6 byte_offset_to_start_of_line: 228 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:12:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:16:00Z"; line_number: 7 byte_offset_to_start_of_line: 271 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:16:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T11:00:00Z"; line_number: 8 byte_offset_to_start_of_line: 325 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T11:00:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T12:10:00Z"; line_number: 9 byte_offset_to_start_of_line: 368 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T12:10:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T14:20:00Z"; line_number: 10 byte_offset_to_start_of_line: 422 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T14:20:00Z"; reason: invalid, message: You are loading data without specifying data format, data will be treated as CSV format by default. If this is not what you mean, please specify data format by --source_format.
[0m12:00:45.064899 [debug] [Thread-1 (]: Traceback (most recent call last):
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/task/base.py", line 363, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/task/base.py", line 310, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/task/base.py", line 410, in run
    return self.execute(compiled_node, manifest)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/task/run.py", line 336, in execute
    return self._execute_model(hook_ctx, context_config, model, context, materialization_macro)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/task/run.py", line 296, in _execute_model
    result = MacroGenerator(
        materialization_macro, context, stack=context["context_macro_stack"]
    )()
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/clients/jinja.py", line 82, in __call__
    return self.call_macro(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt_common/clients/jinja.py", line 395, in call_macro
    return macro(*args, **kwargs)
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 770, in __call__
    return self._invoke(arguments, autoescape)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 109, in macro
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/sandbox.py", line 401, in call
    return __context.call(__obj, *args, **kwargs)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 303, in call
    return __obj(*args, **kwargs)
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/clients/jinja.py", line 82, in __call__
    return self.call_macro(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt_common/clients/jinja.py", line 395, in call_macro
    return macro(*args, **kwargs)
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 770, in __call__
    return self._invoke(arguments, autoescape)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 21, in macro
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/sandbox.py", line 401, in call
    return __context.call(__obj, *args, **kwargs)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 303, in call
    return __obj(*args, **kwargs)
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/clients/jinja.py", line 82, in __call__
    return self.call_macro(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt_common/clients/jinja.py", line 395, in call_macro
    return macro(*args, **kwargs)
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 770, in __call__
    return self._invoke(arguments, autoescape)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 25, in macro
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/sandbox.py", line 401, in call
    return __context.call(__obj, *args, **kwargs)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/jinja2/runtime.py", line 303, in call
    return __obj(*args, **kwargs)
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/adapters/bigquery/impl.py", line 683, in load_dataframe
    self.connections.write_dataframe_to_table(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        client,
        ^^^^^^^
    ...<6 lines>...
        fallback_timeout=300,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/adapters/bigquery/connections.py", line 486, in write_dataframe_to_table
    self._write_file_to_table(client, file_path, table, load_config, fallback_timeout)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/dbt/adapters/bigquery/connections.py", line 518, in _write_file_to_table
    response = job.result(retry=self._retry.create_retry(fallback=fallback_timeout))
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/google/cloud/bigquery/job/base.py", line 1048, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/barbaramariano/repositories/funnel_analysis/.venv/lib/python3.13/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 9; errors: 9; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 9; errors: 9; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:10:00Z"; line_number: 2 byte_offset_to_start_of_line: 50 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:10:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:15:00Z"; line_number: 3 byte_offset_to_start_of_line: 89 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:15:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T09:00:00Z"; line_number: 4 byte_offset_to_start_of_line: 139 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T09:00:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-21T10:20:00Z"; line_number: 5 byte_offset_to_start_of_line: 182 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-21T10:20:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:12:00Z"; line_number: 6 byte_offset_to_start_of_line: 228 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:12:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:16:00Z"; line_number: 7 byte_offset_to_start_of_line: 271 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:16:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T11:00:00Z"; line_number: 8 byte_offset_to_start_of_line: 325 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T11:00:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T12:10:00Z"; line_number: 9 byte_offset_to_start_of_line: 368 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T12:10:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T14:20:00Z"; line_number: 10 byte_offset_to_start_of_line: 422 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T14:20:00Z"; reason: invalid, message: You are loading data without specifying data format, data will be treated as CSV format by default. If this is not what you mean, please specify data format by --source_format.

[0m12:00:45.068724 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '690d303f-8805-4af5-a6a9-a783c6cf1f6e', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15f270650>]}
[0m12:00:45.069446 [error] [Thread-1 (]: 1 of 1 ERROR loading seed file analytics.events ................................ [[31mERROR[0m in 1.73s]
[0m12:00:45.070460 [debug] [Thread-1 (]: Finished running node seed.funnel_analysis.events
[0m12:00:45.071587 [debug] [Thread-7 (]: Marking all children of 'seed.funnel_analysis.events' to be skipped because of status 'error'.  Reason: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 9; errors: 9; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 9; errors: 9; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:10:00Z"; line_number: 2 byte_offset_to_start_of_line: 50 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:10:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:15:00Z"; line_number: 3 byte_offset_to_start_of_line: 89 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:15:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T09:00:00Z"; line_number: 4 byte_offset_to_start_of_line: 139 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T09:00:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-21T10:20:00Z"; line_number: 5 byte_offset_to_start_of_line: 182 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-21T10:20:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:12:00Z"; line_number: 6 byte_offset_to_start_of_line: 228 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:12:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:16:00Z"; line_number: 7 byte_offset_to_start_of_line: 271 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:16:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T11:00:00Z"; line_number: 8 byte_offset_to_start_of_line: 325 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T11:00:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T12:10:00Z"; line_number: 9 byte_offset_to_start_of_line: 368 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T12:10:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T14:20:00Z"; line_number: 10 byte_offset_to_start_of_line: 422 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T14:20:00Z"; reason: invalid, message: You are loading data without specifying data format, data will be treated as CSV format by default. If this is not what you mean, please specify data format by --source_format..
[0m12:00:45.075148 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m12:00:45.075854 [debug] [MainThread]: Connection 'master' was properly closed.
[0m12:00:45.076388 [debug] [MainThread]: Connection 'seed.funnel_analysis.events' was properly closed.
[0m12:00:45.076843 [info ] [MainThread]: 
[0m12:00:45.077305 [info ] [MainThread]: Finished running 1 seed in 0 hours 0 minutes and 2.77 seconds (2.77s).
[0m12:00:45.078073 [debug] [MainThread]: Command end result
[0m12:00:45.106975 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/barbaramariano/repositories/funnel_analysis/target/manifest.json
[0m12:00:45.108778 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/barbaramariano/repositories/funnel_analysis/target/semantic_manifest.json
[0m12:00:45.113777 [debug] [MainThread]: Wrote artifact RunExecutionResult to /Users/barbaramariano/repositories/funnel_analysis/target/run_results.json
[0m12:00:45.114000 [info ] [MainThread]: 
[0m12:00:45.114268 [info ] [MainThread]: [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[0m12:00:45.114463 [info ] [MainThread]: 
[0m12:00:45.114676 [error] [MainThread]: [31mFailure in seed events (seeds/events.csv)[0m
[0m12:00:45.114968 [error] [MainThread]:   400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 9; errors: 9; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 9; errors: 9; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:10:00Z"; line_number: 2 byte_offset_to_start_of_line: 50 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:10:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:15:00Z"; line_number: 3 byte_offset_to_start_of_line: 89 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:15:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T09:00:00Z"; line_number: 4 byte_offset_to_start_of_line: 139 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T09:00:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-21T10:20:00Z"; line_number: 5 byte_offset_to_start_of_line: 182 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-21T10:20:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:12:00Z"; line_number: 6 byte_offset_to_start_of_line: 228 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:12:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T08:16:00Z"; line_number: 7 byte_offset_to_start_of_line: 271 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T08:16:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T11:00:00Z"; line_number: 8 byte_offset_to_start_of_line: 325 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T11:00:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T12:10:00Z"; line_number: 9 byte_offset_to_start_of_line: 368 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T12:10:00Z"; reason: invalid, message: Error while reading data, error message: Invalid datetime string "2025-09-20T14:20:00Z"; line_number: 10 byte_offset_to_start_of_line: 422 column_index: 1 column_name: "event_time" column_type: DATETIME value: "2025-09-20T14:20:00Z"; reason: invalid, message: You are loading data without specifying data format, data will be treated as CSV format by default. If this is not what you mean, please specify data format by --source_format.
[0m12:00:45.116235 [info ] [MainThread]: 
[0m12:00:45.116666 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1
[0m12:00:45.147644 [debug] [MainThread]: Resource report: {"command_name": "seed", "command_success": false, "command_wall_clock_time": 4.9286947, "process_in_blocks": "0", "process_kernel_time": 0.826451, "process_mem_max_rss": "338935808", "process_out_blocks": "0", "process_user_time": 3.250848}
[0m12:00:45.148115 [debug] [MainThread]: Command `dbt seed` failed at 12:00:45.148048 after 4.93 seconds
[0m12:00:45.148425 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15e622fc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15e69cf50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15e69d130>]}
[0m12:00:45.148633 [debug] [MainThread]: Flushing usage events
[0m12:00:45.583338 [debug] [MainThread]: An error was encountered while trying to flush usage events
